apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job-{{ .Values.api.image.tag }}
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: database-migration
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        command: ["npm", "run", "migration:run"]
        env:
          - name: DB_HOST
            value: {{ .Values.database.host }}
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: {{ .Values.database.name }}
          - name: DB_USERNAME
            value: {{ .Values.database.username }}
          - name: DB_PASSWORD
            value: {{ .Values.database.password }}
          - name: ENVIRONMENT
            value: {{ .Values.environment }}
      restartPolicy: Never
  backoffLimit: 1