apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      tier: api
  template:
    metadata:
      labels:
        app: todo
        tier: api
    spec:
      containers:
      - name: todo-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        env:
        - name: DB_HOST
          value: {{ .Values.database.host }}
        - name: DB_NAME
          value: {{ .Values.database.name }}
        - name: DB_USERNAME
          value: {{ .Values.database.username }}
        - name: DB_PASSWORD
          value: {{ .Values.database.password }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 2