name: DIP_CICD
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  build_frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    steps:  
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to AWS ECR
          id: aws-ecr-login
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and push Docker image to AWS ECR
          env:
            ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.FRONTEND_REPO}}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  build_api:
    name: Build and Push API Image
    runs-on: ubuntu-latest
    steps:  
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to AWS ECR
          id: aws-ecr-login
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and push Docker image to AWS ECR
          env:
            ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.API_REPO}}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./api
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  deploy_frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:  
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to AWS ECR
          id: aws-ecr-login
          uses: aws-actions/amazon-ecr-login@v2

        - name: Deploy to AWS EC2 instance
          id: aws-ec2-deploy
          run: |
            command_id=$(aws ssm send-command \
              --instance-ids ${{ vars.AWS_EC2_INSTANCE_ID_1 }} ${{ vars.AWS_EC2_INSTANCE_ID_2 }} \
              --document-name "AWS-RunShellScript" \
              --parameters 'commands = [
                "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.aws-ecr-login.outputs.registry }}",
                "docker stop ${{ vars.FRONTEND_CONTAINER }}",
                "docker pull ${{ steps.aws-ecr-login.outputs.registry }}/${{secrets.FRONTEND_REPO}}:latest",
                "docker run --rm -d -p 80:80 -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} -e ENVIRONMENT=production --name ${{ vars.FRONTEND_CONTAINER }} ${{ steps.aws-ecr-login.outputs.registry }}/${{secrets.FRONTEND_REPO}}:latest"
              ]' --query "Command.CommandId" --output text
            )
            echo "command_id=$command_id" >> $GITHUB_OUTPUT
              
        - name: Wait for deploy step to finish on first EC2 instance
          run: |
            aws ssm wait command-executed \
            --command-id ${{ steps.aws-ec2-deploy.outputs.command_id }} \
            --instance-id ${{ vars.AWS_EC2_INSTANCE_ID_1 }}

        - name: Wait for deploy step to finish on second EC2 instance
          run: |
            aws ssm wait command-executed \
            --command-id ${{ steps.aws-ec2-deploy.outputs.command_id }} \
            --instance-id ${{ vars.AWS_EC2_INSTANCE_ID_2 }}
          
        - name: Deploy result
          run: |
            status=$(aws ssm list-commands --command-id ${{ steps.aws-ec2-deploy.outputs.command_id }} --query "Commands[0].Status" --output text)
            if [ "$status" = "Success" ]; then
              echo "Deployed frontend successfully"
            else
              echo "Frontend deployment failed"
            fi
  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: build_api
    steps:  
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to AWS ECR
          id: aws-ecr-login
          uses: aws-actions/amazon-ecr-login@v2

        - name: Deploy to AWS EC2 instance
          id: aws-ec2-deploy
          run: |
            command_id=$(aws ssm send-command \
              --instance-ids ${{ vars.AWS_EC2_INSTANCE_ID_1 }} ${{ vars.AWS_EC2_INSTANCE_ID_2 }} \
              --document-name "AWS-RunShellScript" \
              --parameters 'commands = [
                "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.aws-ecr-login.outputs.registry }}",
                "docker stop ${{ vars.API_CONTAINER }}",
                "docker pull ${{ steps.aws-ecr-login.outputs.registry }}/${{secrets.API_REPO}}:latest",
                "docker run --rm -d -p 3000:3000 -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} -e ENVIRONMENT=production --name ${{ vars.API_CONTAINER }} ${{ steps.aws-ecr-login.outputs.registry }}/${{secrets.API_REPO}}:latest"
              ]' --query "Command.CommandId" --output text
            )
            echo "command_id=$command_id" >> $GITHUB_OUTPUT
              
        - name: Wait for deploy step to finish on first EC2 instance
          run: |
            aws ssm wait command-executed \
            --command-id ${{ steps.aws-ec2-deploy.outputs.command_id }} \
            --instance-id ${{ vars.AWS_EC2_INSTANCE_ID_1 }}

        - name: Wait for deploy step to finish on second EC2 instance
          run: |
            aws ssm wait command-executed \
            --command-id ${{ steps.aws-ec2-deploy.outputs.command_id }} \
            --instance-id ${{ vars.AWS_EC2_INSTANCE_ID_2 }}
          
        - name: Deploy result
          run: |
            status=$(aws ssm list-commands --command-id ${{ steps.aws-ec2-deploy.outputs.command_id }} --query "Commands[0].Status" --output text)
            if [ "$status" = "Success" ]; then
              echo "Deployed API successfully"
            else
              echo "API deployment failed"
            fi